# Generated by Django 6.0.5 on 2026-05-11 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='브랜드 공식 명칭', max_length=100, unique=True)),
                ('country_code', models.CharField(blank=True, help_text='국가 코드 (KR, FR, UK 등)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_name', models.CharField(help_text='한글 상품명', max_length=255)),
                ('english_name', models.CharField(help_text='영문 상품명', max_length=255)),
                ('product_type', models.CharField(help_text='perfume, cologne 등 기본 분류', max_length=50)),
                ('family', models.CharField(help_text='5대 핵심 계열', max_length=50)),
                ('release_year', models.IntegerField(blank=True, help_text='출시년도', null=True)),
                ('data', models.JSONField(default=dict, help_text='상세 정보 (NoSQL 스타일)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='브랜드 참조', on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='perfumes.brand')),
            ],
            options={
                'unique_together': {('brand', 'english_name')},
            },
        ),
    ]
