# Generated by Django 6.0.5 on 2026-05-11 07:48

import django.db.models.deletion
from django.db import migrations, models


def build_product_info(data):
    return {
        'brand': data.get('brand', ''),
        'korean_name': data.get('korean_name', ''),
        'english_name': data.get('english_name', ''),
        'normalized_name': data.get('normalized_name', ''),
        'product_type': data.get('product_type', ''),
        'product_subtype': data.get('product_subtype', ''),
        'product_url': data.get('product_url', ''),
        'image_url': data.get('image_url', ''),
        'image_asset': data.get('image_asset', {}),
        'price': data.get('price', {}),
        'volume': data.get('volume', ''),
        'meta': {
            'source': data.get('source', ''),
            'source_country': data.get('source_country', ''),
            'release_year': data.get('meta', {}).get('release_year'),
            'original_product_type': data.get('meta', {}).get('original_product_type'),
            'original_country': data.get('meta', {}).get('original_country'),
        },
    }


def copy_product_info(apps, schema_editor):
    PerfumeData = apps.get_model('perfumes', 'PerfumeData')
    PerfumeProductInfo = apps.get_model('perfumes', 'PerfumeProductInfo')

    product_info_rows = []
    for detail in PerfumeData.objects.all().iterator():
        product_info_rows.append(
            PerfumeProductInfo(
                perfume_id=detail.perfume_id,
                data=build_product_info(detail.data or {}),
            )
        )

    if product_info_rows:
        PerfumeProductInfo.objects.bulk_create(product_info_rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_perfumedata_remove_perfume_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='상품 표시와 구매 연결에 필요한 JSON 문서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfume', models.OneToOneField(help_text='정규화된 향수 레코드 참조', on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='perfumes.perfume')),
            ],
            options={
                'verbose_name': 'Perfume Product Info',
                'verbose_name_plural': 'Perfume Product Info',
            },
        ),
        migrations.RunPython(copy_product_info, migrations.RunPython.noop),
    ]
