# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.db import migrations, models


def copy_perfume_data_to_normalized_tables(apps, schema_editor):
    Perfume = apps.get_model("perfumes", "Perfume")
    PerfumeDetail = apps.get_model("perfumes", "PerfumeDetail")
    PerfumeRawData = apps.get_model("perfumes", "PerfumeRawData")
    PerfumeImage = apps.get_model("perfumes", "PerfumeImage")

    for perfume in Perfume.objects.all().iterator():
        data = getattr(perfume, "data", None) or {}
        detail, _ = PerfumeDetail.objects.update_or_create(
            perfume_id=perfume.id,
            defaults={"data": data},
        )
        PerfumeRawData.objects.update_or_create(
            perfume_id=perfume.id,
            defaults={
                "raw_json": data,
                "source_url": data.get("source_url") or data.get("product_url"),
            },
        )
        image_url = str(data.get("image_url") or "").strip()
        if image_url:
            PerfumeImage.objects.update_or_create(
                perfume_detail_id=detail.id,
                original_url=image_url,
                defaults={"processed_path": ""},
            )


def restore_perfume_data(apps, schema_editor):
    Perfume = apps.get_model("perfumes", "Perfume")
    PerfumeDetail = apps.get_model("perfumes", "PerfumeDetail")

    for detail in PerfumeDetail.objects.all().iterator():
        Perfume.objects.filter(id=detail.perfume_id).update(data=detail.data or {})


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0005_remove_perfumeproductinfo_perfume_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfumeDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(default=dict, help_text="서비스용 향수 상세 JSON 문서")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfume",
                    models.OneToOneField(
                        help_text="향수 참조",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="perfumes.perfume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfumeRawData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_json", models.JSONField(default=dict, help_text="변형 전 원본 향수 JSON 문서")),
                ("source_url", models.CharField(blank=True, help_text="원본 페이지 URL", max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "perfume",
                    models.OneToOneField(
                        help_text="향수 참조",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_data",
                        to="perfumes.perfume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfumeImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_url", models.CharField(help_text="원본 이미지 URL", max_length=500)),
                ("processed_path", models.CharField(blank=True, help_text="다운로드 또는 처리된 이미지 경로", max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfume_detail",
                    models.ForeignKey(
                        help_text="향수 상세 참조",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="perfumes.perfumedetail",
                    ),
                ),
            ],
            options={
                "unique_together": {("perfume_detail", "original_url")},
            },
        ),
        migrations.RunPython(copy_perfume_data_to_normalized_tables, restore_perfume_data),
        migrations.RemoveField(
            model_name="perfume",
            name="data",
        ),
    ]
