# Generated by Codex on 2026-05-13

from django.db import migrations


def remove_source_url_from_raw_json(apps, schema_editor):
    PerfumeRawData = apps.get_model("perfumes", "PerfumeRawData")

    for row in PerfumeRawData.objects.all().iterator():
        raw_json = row.raw_json or {}
        if not isinstance(raw_json, dict) or "source_url" not in raw_json:
            continue

        raw_json.pop("source_url", None)
        row.raw_json = raw_json
        row.save(update_fields=["raw_json"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0006_perfume_detail_raw_data_image"),
    ]

    operations = [
        migrations.RunPython(remove_source_url_from_raw_json, noop),
    ]
