# Generated by Codex on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0007_remove_source_url_from_raw_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfumerawdata",
            name="source_url",
        ),
    ]
