# Generated by Codex on 2026-05-13

from django.db import migrations


def remove_image_fields_from_detail_data(apps, schema_editor):
    PerfumeDetail = apps.get_model("perfumes", "PerfumeDetail")

    for detail in PerfumeDetail.objects.all().iterator():
        data = detail.data or {}
        if not isinstance(data, dict):
            continue

        changed = False
        for key in ("image_asset",):
            if key in data:
                data.pop(key, None)
                changed = True

        if changed:
            detail.data = data
            detail.save(update_fields=["data"])


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0009_perfumeimage_base64_data"),
    ]

    operations = [
        migrations.RunPython(remove_image_fields_from_detail_data, migrations.RunPython.noop),
    ]
