# Generated by Codex on 2026-05-13

from django.db import migrations


DETAIL_DATA_KEYS = {
    "price",
    "description",
    "ingredients_raw",
    "notes",
    "accords",
    "keywords",
    "meta",
    "volume",
    "aura_profile",
    "standardized_notes",
    "representative_notes",
    "embedding_doc",
}


def normalize_detail_data(apps, schema_editor):
    PerfumeDetail = apps.get_model("perfumes", "PerfumeDetail")

    for detail in PerfumeDetail.objects.all().iterator():
        data = detail.data or {}
        if not isinstance(data, dict):
            continue

        normalized = {
            key: data[key]
            for key in DETAIL_DATA_KEYS
            if key in data
        }
        if normalized != data:
            detail.data = normalized
            detail.save(update_fields=["data"])


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0010_remove_image_asset_from_perfume_detail"),
    ]

    operations = [
        migrations.RunPython(normalize_detail_data, migrations.RunPython.noop),
    ]
