# Generated by Codex on 2026-05-13

from django.db import migrations


def remove_release_year_from_detail_meta(apps, schema_editor):
    PerfumeDetail = apps.get_model("perfumes", "PerfumeDetail")

    for detail in PerfumeDetail.objects.all().iterator():
        data = detail.data or {}
        if not isinstance(data, dict):
            continue

        meta = data.get("meta")
        if not isinstance(meta, dict) or "release_year" not in meta:
            continue

        meta = dict(meta)
        meta.pop("release_year", None)
        data = dict(data)
        if meta:
            data["meta"] = meta
        else:
            data.pop("meta", None)

        detail.data = data
        detail.save(update_fields=["data"])


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0011_normalize_perfume_detail_data"),
    ]

    operations = [
        migrations.RunPython(remove_release_year_from_detail_meta, migrations.RunPython.noop),
    ]
